apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.cluster.env }}-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "eveid-ui-{{ .Values.cluster.env }}-ip"
spec:
  backend:
    serviceName: {{ .Release.Name }}-{{ .Values.cluster.env }}
    servicePort: 3001